os: osx
osx_image: xcode10.1
rvm: 2.6.0

addons:
  homebrew:
    packages:
    - swiftlint
    update: true

cache:
  - bundler
  - pip

branches:
  only:
    - master
    - develop

env:
  global:
    - PROJECT="JSQCoreDataKit.xcodeproj"
    - SCHEME="JSQCoreDataKit"
    - OSX_SDK=macosx10.14
    - IOS_SDK=iphonesimulator12.1
    - TVOS_SDK=appletvsimulator12.1
    - WATCHOS_SDK=watchsimulator5.1

before_install:
  - pip3 install proselint
  - gem update --system
  - gem install bundler

jobs:
  include:
    - &test
      stage: test
      name: iOS 11.4
      env: DESTINATION="OS=11.4,name=iPhone X" SDK="$IOS_SDK"
      script:
        - set -o pipefail
        - xcodebuild -version -sdk
        - xcodebuild clean test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -enableCodeCoverage YES -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c;
      after_success:
        - bundle exec danger
        - bash <(curl -s https://codecov.io/bash)

    - <<: *test
      name: iOS 12.1
      env: DESTINATION="OS=12.1,name=iPhone X" SDK="$IOS_SDK"
    
    - <<: *test
      name: macOS
      env: DESTINATION="arch=x86_64" SDK="$OSX_SDK"

    - <<: *test
      name: tvOS 12.1
      env: DESTINATION="OS=12.1,name=Apple TV" SDK="$TVOS_SDK"

    - stage: build only
      name: watchOS 5.1
      env: DESTINATION="OS=5.1,name=Apple Watch Series 4 - 40mm" SDK="$WATCHOS_SDK"
      script:
        - xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c;

    - &build-examples
      stage: build examples
      name: iOS 11.4
      env: DESTINATION="OS=11.4,name=iPhone X" SDK="$IOS_SDK"
      script:
        - set -o pipefail
        - xcodebuild -version -sdk
        - xcodebuild clean build -project Example/ExampleApp.xcodeproj -scheme ExampleApp -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c;

    - <<: *build-examples
      name: iOS 12.1
      env: DESTINATION="OS=12.1,name=iPhone X" SDK="$IOS_SDK"

    - stage: lint
      name: pod lint
      script: bundle exec pod lib lint

    - stage: carthage
      osx_image: xcode10.1
      name: carthage
      os: osx
      script: carthage build --no-skip-current --configuration Release

stages:
  - test
  - build only
  - build examples
  - lint
  - carthage
